#!/bin/bash

#clear

# Note:
# 1-port compiler 
# -top_layer m5-m10
# 2-port compiler 
# -top_layer m5-10

/home/gf028/arm/SRAM/sram_dp_hdd_rvt_rvt/r4p0/bin/sram_dp_hdd_rvt_rvt liberty    -name_case upper -mvt "" -ser none -bus_notation on -rcols 2 -rrows 0 -site_def off -check_instname off -frequency 1000 -bmux on -diodes on -activity_factor 50 -words 128   -drive 6 -power_type otc -bits 12 -instname arm_sram_28nm_2p128x12mw4    -retention on -libertyviewstyle nldm -write_mask off -atf off -left_bus_delim "[" -pwr_gnd_rename vddpe:VDDPE,vddce:VDDCE,vsse:VSSE -right_bus_delim "]" -rows_p_bl 128 -wp_size 1 -redundancy off -libname arm_sram_28nm_2p128x12mw4    -write_thru off -cust_comment "This is a memory instance" -pipeline off -prefix "" -mux 4  -top_layer m5-10   -power_gating off -back_biasing off -ema on -corners tt_0p90v_0p90v_25c
/home/gf028/arm/SRAM/sram_dp_hdd_rvt_rvt/r4p0/bin/sram_dp_hdd_rvt_rvt postscript -name_case upper -mvt "" -ser none -bus_notation on -rcols 2 -rrows 0 -site_def off -check_instname off -frequency 1000 -bmux on -diodes on -activity_factor 50 -words 128   -drive 6 -power_type otc -bits 12 -instname arm_sram_28nm_2p128x12mw4    -retention on -libertyviewstyle nldm -write_mask off -atf off -left_bus_delim "[" -pwr_gnd_rename vddpe:VDDPE,vddce:VDDCE,vsse:VSSE -right_bus_delim "]" -rows_p_bl 128 -wp_size 1 -redundancy off -libname arm_sram_28nm_2p128x12mw4    -write_thru off -cust_comment "This is a memory instance" -pipeline off -prefix "" -mux 4  -top_layer m5-10   -power_gating off -back_biasing off -ema on -corners tt_0p90v_0p90v_25c
/home/gf028/arm/SRAM/sram_dp_hdd_rvt_rvt/r4p0/bin/sram_dp_hdd_rvt_rvt verilog    -name_case upper -mvt "" -ser none -bus_notation on -rcols 2 -rrows 0 -site_def off -check_instname off -frequency 1000 -bmux on -diodes on -activity_factor 50 -words 128   -drive 6 -power_type otc -bits 12 -instname arm_sram_28nm_2p128x12mw4    -retention on -libertyviewstyle nldm -write_mask off -atf off -left_bus_delim "[" -pwr_gnd_rename vddpe:VDDPE,vddce:VDDCE,vsse:VSSE -right_bus_delim "]" -rows_p_bl 128 -wp_size 1 -redundancy off -libname arm_sram_28nm_2p128x12mw4    -write_thru off -cust_comment "This is a memory instance" -pipeline off -prefix "" -mux 4  -top_layer m5-10   -power_gating off -back_biasing off -ema on -corners tt_0p90v_0p90v_25c

/home/gf028/arm/SRAM/sram_sp_hsc_rvt_rvt/r5p0/bin/sram_sp_hsc_rvt_rvt liberty    -name_case upper -mvt "" -ser none -bus_notation on -rcols 2 -rrows 0 -site_def off -check_instname off -frequency 1000 -bmux on -diodes on -activity_factor 50 -words 1024  -drive 6 -power_type otc -bits 50 -instname arm_sram_28nm_1p1024x50mw8   -retention on -libertyviewstyle nldm -write_mask off -atf off -left_bus_delim "[" -pwr_gnd_rename vddpe:VDDPE,vddce:VDDCE,vsse:VSSE -right_bus_delim "]" -rows_p_bl 64  -wp_size 1 -redundancy off -libname arm_sram_28nm_1p1024x50mw8   -write_thru off -cust_comment "This is a memory instance" -pipeline off -prefix "" -mux 8  -top_layer m5-m10 -power_gating off -back_biasing off -ema on -corners tt_0p90v_0p90v_25c
/home/gf028/arm/SRAM/sram_sp_hsc_rvt_rvt/r5p0/bin/sram_sp_hsc_rvt_rvt postscript -name_case upper -mvt "" -ser none -bus_notation on -rcols 2 -rrows 0 -site_def off -check_instname off -frequency 1000 -bmux on -diodes on -activity_factor 50 -words 1024  -drive 6 -power_type otc -bits 50 -instname arm_sram_28nm_1p1024x50mw8   -retention on -libertyviewstyle nldm -write_mask off -atf off -left_bus_delim "[" -pwr_gnd_rename vddpe:VDDPE,vddce:VDDCE,vsse:VSSE -right_bus_delim "]" -rows_p_bl 64  -wp_size 1 -redundancy off -libname arm_sram_28nm_1p1024x50mw8   -write_thru off -cust_comment "This is a memory instance" -pipeline off -prefix "" -mux 8  -top_layer m5-m10 -power_gating off -back_biasing off -ema on -corners tt_0p90v_0p90v_25c
/home/gf028/arm/SRAM/sram_sp_hsc_rvt_rvt/r5p0/bin/sram_sp_hsc_rvt_rvt verilog    -name_case upper -mvt "" -ser none -bus_notation on -rcols 2 -rrows 0 -site_def off -check_instname off -frequency 1000 -bmux on -diodes on -activity_factor 50 -words 1024  -drive 6 -power_type otc -bits 50 -instname arm_sram_28nm_1p1024x50mw8   -retention on -libertyviewstyle nldm -write_mask off -atf off -left_bus_delim "[" -pwr_gnd_rename vddpe:VDDPE,vddce:VDDCE,vsse:VSSE -right_bus_delim "]" -rows_p_bl 64  -wp_size 1 -redundancy off -libname arm_sram_28nm_1p1024x50mw8   -write_thru off -cust_comment "This is a memory instance" -pipeline off -prefix "" -mux 8  -top_layer m5-m10 -power_gating off -back_biasing off -ema on -corners tt_0p90v_0p90v_25c
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
/home/gf028/arm/SRAM/sram_sp_hsc_rvt_rvt/r5p0/bin/sram_sp_hsc_rvt_rvt liberty    -name_case upper -mvt "" -ser none -bus_notation on -rcols 2 -rrows 0 -site_def off -check_instname off -frequency 1000 -bmux on -diodes on -activity_factor 50 -words 16384 -drive 6 -power_type otc -bits 12 -instname arm_sram_28nm_1p16384x12mw32 -retention on -libertyviewstyle nldm -write_mask off -atf off -left_bus_delim "[" -pwr_gnd_rename vddpe:VDDPE,vddce:VDDCE,vsse:VSSE -right_bus_delim "]" -rows_p_bl 64  -wp_size 1 -redundancy off -libname arm_sram_28nm_1p16384x12mw32 -write_thru off -cust_comment "This is a memory instance" -pipeline off -prefix "" -mux 32 -top_layer m5-m10 -power_gating off -back_biasing off -ema on -corners tt_0p90v_0p90v_25c
/home/gf028/arm/SRAM/sram_sp_hsc_rvt_rvt/r5p0/bin/sram_sp_hsc_rvt_rvt postscript -name_case upper -mvt "" -ser none -bus_notation on -rcols 2 -rrows 0 -site_def off -check_instname off -frequency 1000 -bmux on -diodes on -activity_factor 50 -words 16384 -drive 6 -power_type otc -bits 12 -instname arm_sram_28nm_1p16384x12mw32 -retention on -libertyviewstyle nldm -write_mask off -atf off -left_bus_delim "[" -pwr_gnd_rename vddpe:VDDPE,vddce:VDDCE,vsse:VSSE -right_bus_delim "]" -rows_p_bl 64  -wp_size 1 -redundancy off -libname arm_sram_28nm_1p16384x12mw32 -write_thru off -cust_comment "This is a memory instance" -pipeline off -prefix "" -mux 32 -top_layer m5-m10 -power_gating off -back_biasing off -ema on -corners tt_0p90v_0p90v_25c
/home/gf028/arm/SRAM/sram_sp_hsc_rvt_rvt/r5p0/bin/sram_sp_hsc_rvt_rvt verilog    -name_case upper -mvt "" -ser none -bus_notation on -rcols 2 -rrows 0 -site_def off -check_instname off -frequency 1000 -bmux on -diodes on -activity_factor 50 -words 16384 -drive 6 -power_type otc -bits 12 -instname arm_sram_28nm_1p16384x12mw32 -retention on -libertyviewstyle nldm -write_mask off -atf off -left_bus_delim "[" -pwr_gnd_rename vddpe:VDDPE,vddce:VDDCE,vsse:VSSE -right_bus_delim "]" -rows_p_bl 64  -wp_size 1 -redundancy off -libname arm_sram_28nm_1p16384x12mw32 -write_thru off -cust_comment "This is a memory instance" -pipeline off -prefix "" -mux 32 -top_layer m5-m10 -power_gating off -back_biasing off -ema on -corners tt_0p90v_0p90v_25c
